// src/components/notes/NoteReader.svelte
<script lang="ts">
  import {
    ChevronDown,
    Minus,
    Pause,
    Play,
    Plus,
    Type,
  } from "@lucide/svelte";
  import type { Note } from "@/lib/types";
  import { formatSemitones, transposeKey } from "@/lib/music/transpose";
  import type { StrokeType } from "@/lib/strumming";
  import Button from "@/components/ui/Button.svelte";
  import Separator from "@/components/ui/Separator.svelte";
  import Slider from "@/components/ui/Slider.svelte";
  import ChordLyricsView from "./ChordLyricsView.svelte";
  import ChordDiagram from "./ChordDiagram.svelte";
  import TabView from "./TabView.svelte";
  import StrummingPreview from "@/components/create/StrummingPreview.svelte";

  const MIN_FONT = 12;
  const MAX_FONT = 26;

  let { note }: { note: Note } = $props();

  let transpose = $state(0);
  let fontSize = $state(16);
  let scrolling = $state(false);
  let speed = $state(30);

  let rafId: number | null = null;
  let lastTs = 0;

  $effect(() => {
    if (!scrolling) {
      if (rafId !== null) {
        cancelAnimationFrame(rafId);
        rafId = null;
        lastTs = 0;
      }
      return;
    }

    const _speed = speed;

    const step = (ts: number) => {
      if (lastTs) {
        const dt = (ts - lastTs) / 1000;
        window.scrollBy(0, _speed * dt);
        const atBottom =
          window.innerHeight + window.scrollY >= document.body.scrollHeight - 1;
        if (atBottom) {
          scrolling = false;
          lastTs = 0;
          rafId = null;
          return;
        }
      }
      lastTs = ts;
      rafId = requestAnimationFrame(step);
    };

    rafId = requestAnimationFrame(step);
    return () => {
      if (rafId !== null) cancelAnimationFrame(rafId);
      lastTs = 0;
    };
  });

  function clampFont(v: number) {
    fontSize = Math.min(MAX_FONT, Math.max(MIN_FONT, v));
  }
</script>

<div>
  <!-- Toolbar -->
  <div
    class="sticky top-14 z-20 -mx-4 mb-6 flex flex-wrap items-center gap-x-4 gap-y-2 border-b border-border/80 bg-background px-4 py-2.5"
  >
    {#if note.type === "chords"}
      <div class="flex items-center gap-1.5">
        <span class="text-xs text-muted-foreground">Transpose</span>
        <Button
          variant="outline"
          size="icon-sm"
          onclick={() => (transpose -= 1)}
          aria-label="Transpose down"
        >
          <Minus />
        </Button>
        <span class="min-w-14 text-center font-mono text-sm">
          {transposeKey(note.key, transpose)}
          <span class="text-muted-foreground">({formatSemitones(transpose)})</span>
        </span>
        <Button
          variant="outline"
          size="icon-sm"
          onclick={() => (transpose += 1)}
          aria-label="Transpose up"
        >
          <Plus />
        </Button>
        {#if transpose !== 0}
          <Button
            variant="ghost"
            size="sm"
            onclick={() => (transpose = 0)}
            class="text-muted-foreground"
          >
            Reset
          </Button>
        {/if}
      </div>
    {/if}

    <Separator orientation="vertical" class="h-6" />

    <div class="flex items-center gap-1.5">
      <Type class="size-4 text-muted-foreground" />
      <Button
        variant="outline"
        size="icon-sm"
        onclick={() => clampFont(fontSize - 1)}
        aria-label="Decrease font size"
      >
        <Minus />
      </Button>
      <span class="w-6 text-center font-mono text-sm">{fontSize}</span>
      <Button
        variant="outline"
        size="icon-sm"
        onclick={() => clampFont(fontSize + 1)}
        aria-label="Increase font size"
      >
        <Plus />
      </Button>
    </div>

    <Separator orientation="vertical" class="h-6" />

    <div class="flex items-center gap-2">
      <Button
        variant={scrolling ? "default" : "outline"}
        size="sm"
        onclick={() => (scrolling = !scrolling)}
      >
        {#if scrolling}
          <Pause />
        {:else}
          <Play />
        {/if}
        Auto-scroll
      </Button>
      <div class="flex w-28 items-center gap-2">
        <Slider bind:value={speed} min={5} max={100} step={5} aria-label="Auto-scroll speed" />
      </div>
    </div>
  </div>

  <!-- Chords used -->
  {#if note.chords.length > 0}
    <div class="mb-6">
      <div class="mb-3 flex items-center gap-2 text-sm font-medium text-muted-foreground">
        <ChevronDown class="size-4" />
        Chords in this note
      </div>
      <div class="flex flex-wrap gap-4">
        {#each note.chords as c}
          <ChordDiagram
            name={transposeKey(c, note.type === "chords" ? transpose : 0)}
            class="w-20"
          />
        {/each}
      </div>
    </div>
  {/if}

  <!-- Strumming pattern -->
  {#if note.strummingPattern?.some((s) => s !== "")}
    <div class="mb-6">
      <p class="mb-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
        Strumming
      </p>
      {#if note.bpm}
        <p class="mb-1.5 font-mono text-sm font-semibold text-foreground">
          {note.bpm} BPM
        </p>
      {/if}
      <StrummingPreview pattern={note.strummingPattern as StrokeType[]} />
    </div>
  {/if}

  <!-- Body -->
  {#if note.type === "chords" && note.chordSheet}
    <ChordLyricsView
      sheet={note.chordSheet}
      {transpose}
      {fontSize}
      tabBlocks={note.tabBlocks}
    />
  {:else if note.tabBlocks?.length}
    <div class="space-y-6">
      {#each note.tabBlocks as block (block.id)}
        <div>
          {#if block.label}
            <p class="mb-2 text-xs font-semibold uppercase tracking-wide text-primary">
              {block.label}
            </p>
          {/if}
          <TabView tab={block.columns} {fontSize} />
        </div>
      {/each}
    </div>
  {/if}
</div>

// src/components/notes/note-reader.tsx

import { useEffect, useRef, useState } from "react";
import {
  ChevronDown,
  Minus,
  Pause,
  Play,
  Plus,
  Type,
} from "lucide-react";

import type { Note } from "@/lib/types";
import { formatSemitones, transposeKey } from "@/lib/music/transpose";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { Slider } from "@/components/ui/slider";
import { ChordLyricsView } from "./chord-lyrics-view";
import { ChordDiagram } from "./chord-diagram";
import { TabView } from "./tab-view";
import { StrummingPreview } from "@/components/create/strumming-editor";

const MIN_FONT = 12;
const MAX_FONT = 26;

export function NoteReader({ note }: { note: Note }) {
  const [transpose, setTranspose] = useState(0);
  const [fontSize, setFontSize] = useState(16);
  const [scrolling, setScrolling] = useState(false);
  const [speed, setSpeed] = useState(30);

  useAutoScroll(scrolling, speed);

  const clampFont = (v: number) =>
    setFontSize(Math.min(MAX_FONT, Math.max(MIN_FONT, v)));

  return (
    <div>
      {/* Toolbar */}
      <div className="sticky top-14 z-20 -mx-4 mb-6 flex flex-wrap items-center gap-x-4 gap-y-2 border-b border-border/80 bg-background px-4 py-2.5">
        {note.type === "chords" && (
          <div className="flex items-center gap-1.5">
            <span className="text-xs text-muted-foreground">Transpose</span>
            <Button
              variant="outline"
              size="icon-sm"
              onClick={() => setTranspose((t) => t - 1)}
              aria-label="Transpose down"
            >
              <Minus />
            </Button>
            <span className="min-w-14 text-center font-mono text-sm">
              {transposeKey(note.key, transpose)}{" "}
              <span className="text-muted-foreground">
                ({formatSemitones(transpose)})
              </span>
            </span>
            <Button
              variant="outline"
              size="icon-sm"
              onClick={() => setTranspose((t) => t + 1)}
              aria-label="Transpose up"
            >
              <Plus />
            </Button>
            {transpose !== 0 && (
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setTranspose(0)}
                className="text-muted-foreground"
              >
                Reset
              </Button>
            )}
          </div>
        )}

        <Separator orientation="vertical" className="h-6" />

        <div className="flex items-center gap-1.5">
          <Type className="size-4 text-muted-foreground" />
          <Button
            variant="outline"
            size="icon-sm"
            onClick={() => clampFont(fontSize - 1)}
            aria-label="Decrease font size"
          >
            <Minus />
          </Button>
          <span className="w-6 text-center font-mono text-sm">{fontSize}</span>
          <Button
            variant="outline"
            size="icon-sm"
            onClick={() => clampFont(fontSize + 1)}
            aria-label="Increase font size"
          >
            <Plus />
          </Button>
        </div>

        <Separator orientation="vertical" className="h-6" />

        <div className="flex items-center gap-2">
          <Button
            variant={scrolling ? "default" : "outline"}
            size="sm"
            onClick={() => setScrolling((s) => !s)}
          >
            {scrolling ? <Pause /> : <Play />}
            Auto-scroll
          </Button>
          <div className="flex w-28 items-center gap-2">
            <Slider
              value={speed}
              min={5}
              max={100}
              step={5}
              onValueChange={(v) => setSpeed(Array.isArray(v) ? v[0] : v)}
              aria-label="Auto-scroll speed"
            />
          </div>
        </div>
      </div>

      {/* Chords used */}
      {note.chords.length > 0 && (
        <div className="mb-6">
          <div className="mb-3 flex items-center gap-2 text-sm font-medium text-muted-foreground">
            <ChevronDown className="size-4" />
            Chords in this note
          </div>
          <div className="flex flex-wrap gap-4">
            {note.chords.map((c) => (
              <ChordDiagram
                key={c}
                name={transposeKey(c, note.type === "chords" ? transpose : 0)}
                className="w-20"
              />
            ))}
          </div>
        </div>
      )}

      {/* Strumming pattern */}
      {note.strummingPattern?.some((s) => s !== "") && (
        <div className="mb-6">
          <p className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
            Strumming
          </p>
          {note.bpm && (
            <p className="mb-1.5 font-mono text-sm font-semibold text-foreground">
              {note.bpm} BPM
            </p>
          )}
          <StrummingPreview pattern={note.strummingPattern as import("@/components/create/strumming-editor").StrokeType[]} />
        </div>
      )}

      {/* Body */}
      {note.type === "chords" && note.chordSheet ? (
        <ChordLyricsView
          sheet={note.chordSheet}
          transpose={transpose}
          fontSize={fontSize}
          tabBlocks={note.tabBlocks}
        />
      ) : note.tabBlocks?.length ? (
        <div className="space-y-6">
          {note.tabBlocks.map((block) => (
            <div key={block.id}>
              {block.label && (
                <p className="mb-2 text-xs font-semibold uppercase tracking-wide text-primary">
                  {block.label}
                </p>
              )}
              <TabView tab={block.columns} fontSize={fontSize} />
            </div>
          ))}
        </div>
      ) : null}
    </div>
  );
}

/** Smoothly scrolls the window while enabled; speed in px/sec. */
function useAutoScroll(enabled: boolean, speed: number) {
  const raf = useRef<number | null>(null);
  const last = useRef<number>(0);

  useEffect(() => {
    if (!enabled) return;

    const step = (ts: number) => {
      if (last.current) {
        const dt = (ts - last.current) / 1000;
        window.scrollBy(0, speed * dt);
        const atBottom =
          window.innerHeight + window.scrollY >=
          document.body.scrollHeight - 1;
        if (atBottom) {
          last.current = 0;
          raf.current = null;
          return;
        }
      }
      last.current = ts;
      raf.current = requestAnimationFrame(step);
    };

    raf.current = requestAnimationFrame(step);
    return () => {
      if (raf.current) cancelAnimationFrame(raf.current);
      last.current = 0;
    };
  }, [enabled, speed]);
}
