// src/App.tsx
import { BrowserRouter, Routes, Route } from "react-router-dom";
import { SiteHeader } from "@/components/layout/site-header";
import { SiteFooter } from "@/components/layout/site-footer";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { FeedPage } from "@/pages/FeedPage";
import { CreatePage } from "@/pages/CreatePage";
import { NotePage } from "@/pages/NotePage";

export function App() {
  return (
    <BrowserRouter>
      <TooltipProvider>
        <div className="dark flex min-h-screen flex-col bg-background text-foreground antialiased">
          <SiteHeader />
          <div className="flex-1">
            <Routes>
              <Route path="/" element={<FeedPage />} />
              <Route path="/create" element={<CreatePage />} />
              <Route path="/notes/:id" element={<NotePage />} />
              <Route path="/notes/:id/edit" element={<CreatePage />} />
            </Routes>
          </div>
          <SiteFooter />
          <Toaster />
        </div>
      </TooltipProvider>
    </BrowserRouter>
  );
}

// src/App.svelte
<script lang="ts">
  import Router from "svelte-spa-router";
  import SiteHeader from "@/components/layout/SiteHeader.svelte";
  import SiteFooter from "@/components/layout/SiteFooter.svelte";
  import { Toaster } from "svelte-sonner";
  import FeedPage from "@/pages/FeedPage.svelte";
  import CreatePage from "@/pages/CreatePage.svelte";
  import NotePage from "@/pages/NotePage.svelte";

  const routes = {
    "/": FeedPage,
    "/create": CreatePage,
    "/notes/:id/edit": CreatePage,
    "/notes/:id": NotePage,
  };
</script>

<div class="flex min-h-screen flex-col bg-background text-foreground antialiased">
  <SiteHeader />
  <div class="flex-1">
    <Router {routes} />
  </div>
  <SiteFooter />
  <Toaster theme="dark" richColors />
</div>
